"""Public Spectrum Core API."""

from .pack import (
    EncryptOptions,
    EncryptedPackInfo,
    ExternalEntry,
    InvalidPassphraseError,
    LockedPackError,
    PackEntry,
    SpectrumPack,
    append_to_pack,
    decode_member,
    decrypt_pack_bytes,
    encrypt_pack_bytes,
    export_distributable,
    inspect_encrypted_header,
    inspect_pack,
    is_encrypted_pack,
    is_external_media_file,
    is_generated_path,
    pack,
    unpack,
)
from .spec import (
    DecodeResult,
    EncodeResult,
    SpecInfo,
    decode_file,
    encode_file,
    inspect_spec,
)
from .validation import (
    ValidationReport,
    verify_pack,
    verify_pack_sources,
    verify_path,
    verify_spec,
)

__all__ = [
    "DecodeResult",
    "EncryptOptions",
    "EncryptedPackInfo",
    "ExternalEntry",
    "EncodeResult",
    "InvalidPassphraseError",
    "LockedPackError",
    "PackEntry",
    "SpecInfo",
    "SpectrumPack",
    "ValidationReport",
    "append_to_pack",
    "decode_file",
    "decode_member",
    "decrypt_pack_bytes",
    "encode_file",
    "encrypt_pack_bytes",
    "export_distributable",
    "inspect_encrypted_header",
    "inspect_pack",
    "inspect_spec",
    "is_encrypted_pack",
    "is_external_media_file",
    "is_generated_path",
    "pack",
    "unpack",
    "verify_pack",
    "verify_pack_sources",
    "verify_path",
    "verify_spec",
]
